### ISSUE TITLE
Crash on servers trying to load Flywheel on SERVER DIST

### ISSUE THREAD

**Issue by SrRapero720** [RuochenFu21/CreateMoreDrillHeads#1]
Create no requires Flywheel on server, because flywheel is a render engine and server no needs to render

**Comment by SrRapero720** [comment]
CRASH REPORT
[crash-2023-04-01_20.45.52-fml.txt](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/11130563/crash-2023-04-01_20.45.52-fml.txt)

**Comment by furuochen-dev** [comment]
hmm

**Comment by furuochen-dev** [comment]
this might be a create version incompatibility, but I'll check

**Comment by furuochen-dev** [comment]
Fixed!
