### ISSUE TITLE
Quartz crushing recipe conflicts

### ISSUE THREAD

**Issue by reasure3** [RuochenFu21/CreateMoreDrillHeads#17]
Looking at JEI, when crushing quartz, there are recipes that produce quartz dust and also recipes that produce experience nuggets.
However, when I actually crush quartz, it seems like the recipes that produce experience nuggets are ignored.
Is there a way to get experience nuggets?

**Comment by furuochen-dev** [comment]
Why closed?

**Comment by reasure3** [comment]
Sorry, It was conflicts with Create: Stuff and Addition

**Comment by furuochen-dev** [comment]
oh ok
