### ISSUE TITLE
Drills cant be used with Contraption controller or in contraptions

### ISSUE THREAD

**Issue by SrRapero720** [RuochenFu21/CreateMoreDrillHeads#2]
# First: Drills can't be used on Contraption controller filter
When filter is enabled affects only andesite drills but no extended one
![image](https://github.com/RuochenFu21/CreateMoreDrillHeads/assets/29090346/768f8e86-9bd3-4a5d-99ff-d182c55b4cbc)

# Second: Drills on contraptions get default texture and not keeps minning boost.
![2023-06-10_03h30_06](https://github.com/RuochenFu21/CreateMoreDrillHeads/assets/29090346/323e7682-ff89-4d4c-bcc5-f23d7937437a)
![2023-06-10_03h30_11](https://github.com/RuochenFu21/CreateMoreDrillHeads/assets/29090346/5bb225db-e5a8-4d9b-b502-90e41fa2adf4)

**Comment by furuochen-dev** [comment]
Second one is known

**Comment by furuochen-dev** [comment]
First one hmmmmm

**Comment by furuochen-dev** [comment]
Fixed in 2.0.0
