### ISSUE TITLE
Crash on Arclight due to NoClassDefFoundError

### ISSUE THREAD

**Issue by GLDYM** [RuochenFu21/CreateMoreDrillHeads#5]
When loading this mod on arclight with create-0.5.1c,  the server crashed; but it didn't cause crash on client side. I think the crash was caused by this mod but not arclight.
Here is the crash-report.
[crash-2023-09-07_15.06.19-fml.txt](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/12545834/crash-2023-09-07_15.06.19-fml.txt)

**Comment by furuochen-dev** [comment]
this could be a problem with arclight

**Comment by furuochen-dev** [comment]
Is this your first time initialising the game?

**Comment by furuochen-dev** [comment]
Maybe try load without arclight

**Comment by GLDYM** [comment]
> Maybe try load without arclight

It's the first time initialising the game. When loading without arclight, it crashed too.
[crash-2023-09-08_18.35.42-fml.txt](https://github.com/RuochenFu21/CreateMoreDrillHeads/files/12558512/crash-2023-09-08_18.35.42-fml.txt)

**Comment by furuochen-dev** [comment]
Mod version, create mod version, minecraft version pls

**Comment by GLDYM** [comment]
> Mod version, create mod version, minecraft version pls

All the information shows in the crash-report.
Mod version: 1.18.2-v2.0.2
create mod version: 0.5.1c

**Comment by furuochen-dev** [comment]
Hm

**Comment by furuochen-dev** [comment]
What mod you have except for this one

**Comment by GLDYM** [comment]
> What mod you have except for this one

None

**Comment by furuochen-dev** [comment]
Check if creating a separate world on client crashes the game too

**Comment by GLDYM** [comment]
It doesn't crash on client side.
I think the game crash because of using a class that not existing on the server side, as the crash-report shows.

**Comment by furuochen-dev** [comment]
Just checkin', because I do think I fixed this on v1.3

**Comment by furuochen-dev** [comment]
Welp I think I'll try to fix this the next time I update this mod

**Comment by furuochen-dev** [comment]
Could also be a duplicate of #11

**Comment by furuochen-dev** [comment]
Fixed in 2.0.3
