### ISSUE TITLE
Missing refmap

### ISSUE THREAD

**Issue by Xyphenore** [RuochenFu21/CreateMoreDrillHeads#6]
**Describe the bug**

Warning about the missing refmap.

The warning from the console:

'Reference map 'createmoredrillheads.refmap.json' for createmoredrillheads.mixins.json could not be read. If this is a development environment you can ignore this message'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.

**Additional context**
- Mod version: 2.0.2 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by furuochen-dev** [comment]
Does the game crash? Warnings are not a big deal

**Comment by Xyphenore** [comment]
The game works good, just the warning is printed.

**Comment by furuochen-dev** [comment]
Does't sound like a problem

**Comment by furuochen-dev** [comment]
Thanks for reporting tho
