### ISSUE TITLE
Can't craft the Netherite drill

### ISSUE THREAD

**Issue by Xyphenore** [RuochenFu21/CreateMoreDrillHeads#7]
**Describe the bug**

The netherite drill is not craftable, and JEI don't show the receipe.

The error from the console:

'Parsing error loading recipe createmoredrillheads:netherite_drill
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'minecraft:smithing''

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world.
- Error is printed to console.
- Try to craft the netherite drill.

**Additional context**
- Mod version: 2.0.2 for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by furuochen-dev** [comment]
Gotcha, I forgot the smithing table change, I'll fix this when I got time

**Comment by furuochen-dev** [comment]
Fixed in 2.0.3
