### ISSUE TITLE
Error during the loading of mod with Create 0.5.1e

### ISSUE THREAD

**Issue by Xyphenore** [RuochenFu21/CreateMoreDrillHeads#8]
**Describe the bug**

When loading the game with Create 0.5.1e and the mod, the game starts and stay on the windows 'Error loading mods'. The game is unplayed.

The error on console: 'Failed to create mod instance. ModID: createmoredrillheads, class com.forsteri.createmoredrillheads.CreateMoreDrillHeads
java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)''

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Create a world.
- Error is printed to console.

**Additional context**
- Mod version: 2.0.2 for 1.20.1
- Forge version: 47.2.1
- Create version: 0.5.1e for 1.20.1

**Comment by Amronos** [comment]
+1

**Comment by billjk2013** [comment]
+1

**Comment by billjk2013** [comment]
+1 i'm also  having this issue with this mod and a few other reate addons

**Comment by OromisElf** [comment]
I put my crashlogs for this on the discord
([here's](https://mclo.gs/tEdKCDf) the one for 0.5.1e)

**Comment by furuochen-dev** [comment]
Fixed in 2.0.3
